<a href="https://colab.research.google.com/github/Soyluisflores/Clases/blob/main/Clase_24_Octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Flores Hernández Luis Alberto
Clase 13
Numpy

In [ ]:
#Arreglos
import numpy as np
arr = np.array([1, 2 , 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
#Phyton toma encuenta el 0 la momento de tomar elementos
arr = np.array([1, 8, 6, 3, 7])

print(arr[0:3])

[1 8 6]


In [ ]:
#Al imprimir -1 toma el último elemento
arr = np.array([1, 2 , 3, 4, 5, 6, 7])

print(arr[-1])

7


In [ ]:
#Avanzando de 2 en 2 sin tomarencuenta el elemento en la poscicion 5
arr = np.array([1, 2 , 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
#Avanza de 2 en 2
arr = np.array([1, 2 , 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
#Imprime todo
arr = np.array([1, 2 , 3, 4, 5, 6, 7])

print(arr[::1])

[1 2 3 4 5 6 7]


In [ ]:
#Imprime todo
arr = np.array([1, 2 , 3, 4, 5, 6, 7])

print(arr[0::])

[1 2 3 4 5 6 7]


In [ ]:
# Imprime lista vacia
arr = np.array([1, 2 , 3, 4, 5, 6, 7])

print(arr[:0])

[]


In [ ]:
#Escoge elementos específicos en el renglón
arr = np.array([[1, 2 , 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
#Toma todos los elementos de una renglón
rr = np.array([[1, 2 , 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, ::])

[ 6  7  8  9 10]


In [ ]:
#Selecciona elementos específicos en la columna al escirbir ":"
arr = np.array([[1, 2 , 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
#Toma todo el renglón
arr = np.array([[1, 2 , 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:1])

[[1 2 3 4 5]]


In [ ]:
#Fija el elemento 3 del renglon y columna
arr = np.array([[1, 2 , 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,3])

[4 9]


In [ ]:
#Fija todos los elementos
arr = np.array([[1, 2 , 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#Toma elementos especificos del renglon y la columna
arr = np.array([[1, 2 , 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
#Intersecta leementos,aunque el elemento núm.5 no sea un elemento existente
arr = np.array([[1, 2 , 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:1, 2:5])

[[3 4 5]]


In [ ]:
#Intersecta leementos,aunque el elemento núm.6 no sea un elemento existente
arr = np.array([[1, 2 , 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:1, 2:6])

[[3 4 5]]


In [4]:
# Devuelve Arreglo con índices
import numpy as np
arr = np.array([1, 2 , 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [8]:
#Buscar
arr = np.array([1, 2 , 3, 4, 5, 6, 7, 8])

x = np.searchsorted(arr,4)
print(x)

3


In [ ]:
#Filtrar
arr = np.array([1, 2 , 3, 4, 5, 6, 7, 8])
filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False False False False False False False]
[]


In [ ]:
#Suma
x=np.array([1, 2, 3])
y=np.array([4, 5, 6])


In [ ]:
suma =x+y
print(f"La suma es {suma}")

La suma es [5 7 9]


In [ ]:
#Multiplicacion
mult=x*y
print(f"La multiplicacion es {mult}")

La multiplicacion es [ 4 10 18]


In [ ]:
#Resta
min=x-y
print(f"La resta es {min}")

La resta es [-3 -3 -3]


In [ ]:
#Division
div=x/y
print(f"La division es {div}")

La division es [0.25 0.4  0.5 ]


In [ ]:
#Numero pi
import math
print(math.pi)

3.141592653589793


In [ ]:
#Calcular el seno
angulos=np.array([0,np.pi/2,np.pi])
seno=np.sin(angulos)
print(f"Los senos{seno}")
print(f"De los angulos{angulos}")

Los senos[0.0000000e+00 1.0000000e+00 1.2246468e-16]
De los angulos[0.         1.57079633 3.14159265]


In [ ]:
#Crear una lista de Arreglos con Range
x=np.array(list(range(1,8)))
print(x)

[1 2 3 4 5 6 7]


In [ ]:
x=np.array(list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


In [ ]:
#Convertir arreglo en matriz con reshape
matriz=x.reshape(2,4)
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
x.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
#Shape
x.reshape(4,2).shape

(4, 2)

In [ ]:
#Obtener partes específicas de lintervalo diviendo en partes insetando elnumero de puntos
x=np.linspace(0,1,4)
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
x=np.linspace(0,1,2)
x

array([0., 1.])

In [ ]:
#Tomar elementos Aleatorios
np.random.uniform(0,1,6)

array([0.06095864, 0.6086342 , 0.76683999, 0.87010274, 0.50548608,
       0.55582598])

In [ ]:
#Tomar numeros aleatorios enteros
x=np.linspace(0,1,4)
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
#Tomar elementos aleatorios cdefiniendo el tamaño
x=np.random.randint(0,10,size=1)
x

array([5])

In [ ]:
#Pedir al usuario un numero del 1-10 y adivinarlo usando randint
numero = int(input("Ingresa numero del 1 al 10:"))
numero_aleatorio= np.random.randint(1,10,size=1)
if numero == numero_aleatorio:
  print(f"Correcto{numero_aleatorio}")
else:
  print(f"Incorrecto{numero_aleatorio}")

Ingresa numero del 1 al 10:1
Correcto[1]
