<a href="https://colab.research.google.com/github/Soyluisflores/Clases/blob/main/Clase_19Oct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nombre: Flores Hernández Luis Alberto
Clase 19 de Octubre

In [ ]:
#Arreglos
import numpy as np

arr =np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array(42)

print(arr)

42


In [ ]:
#Arreglos 2D (BIDIMENCIONALES)

arr = np.array([[1, 2,3], [14, 5, 6]])

print(arr)

[[ 1  2  3]
 [14  5  6]]


In [ ]:
#Arreglos 3D (Tridimencionales)

arr= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#Dimensiones y shape

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2,3], [14, 5, 6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [ ]:
#Acceder a los elementos

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0, 1, 2])

6


In [ ]:
#suma de elementos de una matriz con numpy
arr = np.array([[1, 1, 1], [1, 1, 1], [1,1,1]])

suma_elementos=np.sum(arr)

print(suma_elementos)

9


In [ ]:
#suma de elementos de una matriz con listas
A=[[1, 1, 1], [1, 1, 1], [1, 1, 1]]

suma=0
for i in range(len(A)):
  for j in range(len(A)):
    suma=suma+A[i][j]
print(f"la suma es {suma}")

la suma es 9


In [ ]:
#producto punto con numpy
arr = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])

PRODUCTO_ESCALAR=np.sum(arr, axis=1)

print(PRODUCTO_ESCALAR)

[ 6 15 24]


In [ ]:
def ProductoPunto(a,b):
  PP = 0,0
  for i in range(len(a)):
    PP= PP+a[i]*b[i]
  return PP

In [5]:
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr3 = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
Pp_por_reng = np.array([0, 0, 0])
Pp_por_col = np.array([0, 0, 0])

In [21]:
import numpy as np

def AgarraCol(a,col):
    nuevo=[]
    for i in range(len(a)):
      nuevo.append(a[i, col])

    return np.array (nuevo)

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
columna = AgarraCol(matriz, 1)
print(columna)

[2 5 8]
